### ISSUE TITLE
Where to cite your paper

### ISSUE THREAD

**Issue by TicusFFF** [seewoo5/KT#4]
Hi, I appreciate your work very much. You have reproduced many classic KT models, which is very helpful to people who study KT.

I want to quote your recurring results in my paper, especially the recurring results of DKVMN.
Do you have any papers that record the recurring results? I want to cite it. ^_^

**Comment by seewoo5** [comment]
If you are mentioning the tables with AUC/ACCs I put on README, unfortunately I don't have any published paper with the results since this is just a personal project that aims to implement as much as KT models with pytorch. I think it is possible to [cite github repository](https://academia.stackexchange.com/questions/14010/how-do-you-cite-a-github-repository), but I really recommend you to run the experiments again (with the hyperparameters I recorded or you can do further search) and report that results.

**Comment by TicusFFF** [comment]
Thank you for your reply and suggestions. I will cite this github repository and rerun experiments.
